services:
  db-postgres:
    image: postgres:13-alpine
    container_name: db_postgres
    restart: always
    environment:
      postgres_db: ${DB_NAME}
      postgres_user: ${DB_USER}
      postgres_password: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  backend-core:
    build: .
    container_name: backend
    depends_on:
      - db-postgres
    ports:
      - "8080:8080"
    environment:
      spring_datasource_url: ${DB_URL}
      spring_datasource_username: ${DB_USER}
      spring_datasource_password: ${DB_PASSWORD}